// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || loong64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfLatencyEvent struct {
	LatencyNs uint64
	SyscallId uint32
	Pid       uint32
	Tid       uint32
	_         [4]byte
	Ret       int64
	Comm      [16]int8
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	TraceSyscallEnter *ebpf.ProgramSpec `ebpf:"trace_syscall_enter"`
	TraceSyscallExit  *ebpf.ProgramSpec `ebpf:"trace_syscall_exit"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Events        *ebpf.MapSpec `ebpf:"events"`
	StartTimes    *ebpf.MapSpec `ebpf:"start_times"`
	SyscallFilter *ebpf.MapSpec `ebpf:"syscall_filter"`
	SyscallIds    *ebpf.MapSpec `ebpf:"syscall_ids"`
	TargetComm    *ebpf.MapSpec `ebpf:"target_comm"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Events        *ebpf.Map `ebpf:"events"`
	StartTimes    *ebpf.Map `ebpf:"start_times"`
	SyscallFilter *ebpf.Map `ebpf:"syscall_filter"`
	SyscallIds    *ebpf.Map `ebpf:"syscall_ids"`
	TargetComm    *ebpf.Map `ebpf:"target_comm"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.StartTimes,
		m.SyscallFilter,
		m.SyscallIds,
		m.TargetComm,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	TraceSyscallEnter *ebpf.Program `ebpf:"trace_syscall_enter"`
	TraceSyscallExit  *ebpf.Program `ebpf:"trace_syscall_exit"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.TraceSyscallEnter,
		p.TraceSyscallExit,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
