// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || loong64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfLatencyEvent struct {
	Dev       uint32
	Pad       uint32
	LatencyNs uint64
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	BlockRqComplete *ebpf.ProgramSpec `ebpf:"block_rq_complete"`
	BlockRqIssue    *ebpf.ProgramSpec `ebpf:"block_rq_issue"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	DevFilter *ebpf.MapSpec `ebpf:"dev_filter"`
	Events    *ebpf.MapSpec `ebpf:"events"`
	LatConfig *ebpf.MapSpec `ebpf:"lat_config"`
	ReqStart  *ebpf.MapSpec `ebpf:"req_start"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	DevFilter *ebpf.Map `ebpf:"dev_filter"`
	Events    *ebpf.Map `ebpf:"events"`
	LatConfig *ebpf.Map `ebpf:"lat_config"`
	ReqStart  *ebpf.Map `ebpf:"req_start"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.DevFilter,
		m.Events,
		m.LatConfig,
		m.ReqStart,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	BlockRqComplete *ebpf.Program `ebpf:"block_rq_complete"`
	BlockRqIssue    *ebpf.Program `ebpf:"block_rq_issue"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.BlockRqComplete,
		p.BlockRqIssue,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
